// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmuPaJWdJJc-Ct5Fxkt9DRicAu4boyn-k',
    appId: '1:281627900338:web:043a09a31c1e6cdeae0cab',
    messagingSenderId: '281627900338',
    projectId: 'ashub-7fc0f',
    authDomain: 'ashub-7fc0f.firebaseapp.com',
    storageBucket: 'ashub-7fc0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_PIdv_nxf2eDn7eYc8NLEGT_0PX73wQM',
    appId: '1:281627900338:android:a3225be58f25d25dae0cab',
    messagingSenderId: '281627900338',
    projectId: 'ashub-7fc0f',
    storageBucket: 'ashub-7fc0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGuSZGRKUMuzHsdE2fp7RIYUwyXK-RibI',
    appId: '1:281627900338:ios:66f3f63fba1f20f8ae0cab',
    messagingSenderId: '281627900338',
    projectId: 'ashub-7fc0f',
    storageBucket: 'ashub-7fc0f.firebasestorage.app',
    iosBundleId: 'com.example.ashub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGuSZGRKUMuzHsdE2fp7RIYUwyXK-RibI',
    appId: '1:281627900338:ios:66f3f63fba1f20f8ae0cab',
    messagingSenderId: '281627900338',
    projectId: 'ashub-7fc0f',
    storageBucket: 'ashub-7fc0f.firebasestorage.app',
    iosBundleId: 'com.example.ashub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmuPaJWdJJc-Ct5Fxkt9DRicAu4boyn-k',
    appId: '1:281627900338:web:f4a359688e6b1635ae0cab',
    messagingSenderId: '281627900338',
    projectId: 'ashub-7fc0f',
    authDomain: 'ashub-7fc0f.firebaseapp.com',
    storageBucket: 'ashub-7fc0f.firebasestorage.app',
  );

}